### ISSUE TITLE
Not all pages have html/head

### ISSUE THREAD

**Issue by haginom** [fac22/week2-AAMJ#29]
Sorry again if I'm totally misunderstanding: 

It looks like your different routes "/", "/users/add" and "/user" don't all have the html head etc: (<!doctype html><html><head>). 

So you don't have to duplicate code all that code in each route, you could have a component folder with a function that returns all that html stuff as a template so you could use it across all your routes. (Oli showed something similar in code review last week) 

function homepage(content) {
 const html = /*html*/ `
  <!doctype html>
      <html>....

... <body>${content}</body>

`
return html
}

**Comment by jijip41** [comment]
fixed it :) thanks!
